# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rover_msgs/CameraMotion.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CameraMotion(genpy.Message):
  _md5sum = "e9f74620875109c0323fbfee10cf0d8f"
  _type = "rover_msgs/CameraMotion"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 X_button
int32 B_button
int32 Y_button
int32 A_button
int32 reset_flag

"""
  __slots__ = ['X_button','B_button','Y_button','A_button','reset_flag']
  _slot_types = ['int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       X_button,B_button,Y_button,A_button,reset_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CameraMotion, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.X_button is None:
        self.X_button = 0
      if self.B_button is None:
        self.B_button = 0
      if self.Y_button is None:
        self.Y_button = 0
      if self.A_button is None:
        self.A_button = 0
      if self.reset_flag is None:
        self.reset_flag = 0
    else:
      self.X_button = 0
      self.B_button = 0
      self.Y_button = 0
      self.A_button = 0
      self.reset_flag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5i().pack(_x.X_button, _x.B_button, _x.Y_button, _x.A_button, _x.reset_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.X_button, _x.B_button, _x.Y_button, _x.A_button, _x.reset_flag,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5i().pack(_x.X_button, _x.B_button, _x.Y_button, _x.A_button, _x.reset_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.X_button, _x.B_button, _x.Y_button, _x.A_button, _x.reset_flag,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
